### ISSUE TITLE
watcher not work

### ISSUE THREAD

**Issue by wofengletian** [php-zookeeper/php-zookeeper#17]
`class ZookeeperDemo extends Zookeeper
{
    public function watcher($i, $type, $key)
    {
        echo 'watcher working';
        // Watcher gets consumed so we need to set a new one
        $this->get('/test', array($this, 'watcher'));
    }
}
$zoo = new ZookeeperDemo();
$zoo->connect('127.0.0.1:2181');
$zoo->get('/test', [$zoo,'watcher']);
while (true) {
    echo '.';
    sleep(2);
}`

i set /test other value in client, nothing echo.
php:PHP 7.0.20-2 (cli) (built: Jun 14 2017 05:30:04) ( NTS )

**Comment by Timandes** [comment]
Could you show me more details, like version info?

**Comment by zhengide** [comment]
@Timandes 
I meet the same problem.
My PHP version is 7.0.20, php-zookeeper version is 0.5.0, zookeeper client version is 3.4.12.
But I find it works well with PHP 7.1.15.

>PHP Version => 7.0.20
>Server API => Command Line Interface
>Virtual Directory Support => disabled
>
>PHP API => 20151012
>PHP Extension => 20151012
>Zend Extension => 320151012
>Zend Extension Build => API320151012,NTS
>PHP Extension Build => API20151012,NTS
>Debug Build => no
>Thread Safety => disabled
>Zend Signal Handling => enabled
>Zend Memory Manager => enabled
>Zend Multibyte Support => provided by mbstring
>IPv6 Support => enabled
>DTrace Support => disabled
>
>Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
>Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
>Registered Stream Filters => zlib.*, convert.iconv.*, mcrypt.*, mdecrypt.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
>
>This program makes use of the Zend Scripting Language Engine:
>Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>    with Zend OPcache v7.0.20, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Timandes** [comment]
Sorry for my late response.
And this is the formatted fragment(- -|||):
```
<?php

class ZookeeperDemo extends Zookeeper
{
    public function watcher($i, $type, $key) 
    { 
        echo 'watcher working'; // Watcher gets consumed so we need to set a new one 
        $this->get('/test', array($this, 'watcher')); 
    } 
} 

$zoo = new ZookeeperDemo(); 
$zoo->connect('127.0.0.1:2181'); 
$zoo->get('/test', [$zoo,'watcher']); 
while (true) { 
    echo '.'; 
    sleep(2); 
}
```
----

Before PHP 7.1, you should `declare(ticks=1);`[3] to enable callbacks:
```
<?php

declare(ticks=1);

class ZookeeperDemo extends Zookeeper
{
...
```
just like using `pcntl_signal`[1].

Or you could trigger callbacks manually by calling `zookeeper_dispatch()`[2]:
```
...
while (true) { 
    echo '.'; 
    sleep(2); 
    zookeeper_dispatch();
}
```

PHP 7.1 or greater could use `EG(vm_interrupt)` to implement async dispatch. So John Boehr[4] did some work to use that to trigger callbacks automatically (See Issue #8 ). That's why PHP 7.1.15 works fine.

[1] http://php.net/manual/en/function.pcntl-signal.php
[2] I could not find any document related to this function. It's my fault.
[3] http://php.net/manual/en/control-structures.declare.php#control-structures.declare.ticks
[4] https://github.com/jbboehr
